CLASS zzlrn_bp_s4d400_r_flight DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zzlrn_s4d400_r_flight .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zzlrn_bp_s4d400_r_flight IMPLEMENTATION.
ENDCLASS.
