CLASS zbp_s4d400_r_flight DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zs4d400_r_flight .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zbp_s4d400_r_flight IMPLEMENTATION.
ENDCLASS.
